### ISSUE TITLE
Bug: Exiting a Room Should Make the Player Enter the New Scene Through the Corresponding Entrance

### ISSUE THREAD

**Issue by BeafCultist** [gmuGADIG/FetchQuest#139] opened 2024-10-24 01:15 UTC
Right now it just resets the scene, which is weird. Especially since we're gonna have rooms with multiple entrances and stuff.

**Comment by micycle8778** [comment] 2024-10-24 21:38
duplicate of #130

**Closed by micycle8778** 2024-10-24 21:38 UTC
Labels: bug, World
